Process ReplayBufferAsync-2:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chengzilong/DDQN/ReplayBufferAsync2.py", line 86, in run
    print(self.out_pointer, self.in_pointer, self.current_cache_size)
AttributeError: 'ReplayBufferAsync' object has no attribute 'out_pointer'
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 201, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 743, in communicate_stop_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 545, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 550, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 183, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 755, in communicate_network_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 545, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 550, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
