2021-06-18 04:14:53,904 INFO    MainThread:4069749 [internal.py:wandb_internal():91] W&B internal server running at pid: 4069749, started at: 2021-06-18 04:14:53.903612
2021-06-18 04:14:53,915 INFO    WriterThread:4069749 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/offline-run-20210618_041452-2cql5cgu/run-2cql5cgu.wandb
2021-06-18 04:14:53,917 DEBUG   HandlerThread:4069749 [handler.py:handle_request():124] handle_request: run_start
2021-06-18 04:14:56,082 DEBUG   HandlerThread:4069749 [meta.py:__init__():39] meta init
2021-06-18 04:14:56,082 DEBUG   HandlerThread:4069749 [meta.py:__init__():53] meta init done
2021-06-18 04:14:56,082 DEBUG   HandlerThread:4069749 [meta.py:probe():210] probe
2021-06-18 04:14:56,089 DEBUG   HandlerThread:4069749 [git.py:repo():33] git repository is invalid
2021-06-18 04:14:56,089 DEBUG   HandlerThread:4069749 [meta.py:_save_pip():57] save pip
2021-06-18 04:14:56,091 DEBUG   HandlerThread:4069749 [meta.py:_save_pip():71] save pip done
2021-06-18 04:14:56,092 DEBUG   HandlerThread:4069749 [meta.py:_save_conda():78] save conda
2021-06-18 04:15:00,473 DEBUG   HandlerThread:4069749 [meta.py:_save_conda():86] save conda done
2021-06-18 04:15:00,474 DEBUG   HandlerThread:4069749 [meta.py:probe():252] probe done
2021-06-18 04:15:01,968 WARNING MainThread:4069749 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-06-18 04:15:02,102 WARNING MainThread:4069749 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-06-18 04:15:02,102 ERROR   MainThread:4069749 [internal.py:wandb_internal():150] Internal process interrupted.
2021-06-18 04:15:02,108 INFO    HandlerThread:4069749 [handler.py:finish():638] shutting down handler
2021-06-18 04:15:02,108 INFO    WriterThread:4069749 [datastore.py:close():288] close: /home/chengzilong/DDQN/wandb/offline-run-20210618_041452-2cql5cgu/run-2cql5cgu.wandb
2021-06-18 04:15:02,425 INFO    MainThread:4069749 [internal.py:handle_exit():78] Internal process exited
