2021-06-17 16:45:34,467 INFO    MainThread:2324483 [internal.py:wandb_internal():91] W&B internal server running at pid: 2324483, started at: 2021-06-17 16:45:34.466532
2021-06-17 16:45:34,477 INFO    WriterThread:2324483 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/offline-run-20210617_164532-3u0x1kar/run-3u0x1kar.wandb
2021-06-17 16:45:34,478 DEBUG   HandlerThread:2324483 [handler.py:handle_request():124] handle_request: run_start
2021-06-17 16:45:36,755 DEBUG   HandlerThread:2324483 [meta.py:__init__():39] meta init
2021-06-17 16:45:36,755 DEBUG   HandlerThread:2324483 [meta.py:__init__():53] meta init done
2021-06-17 16:45:36,756 DEBUG   HandlerThread:2324483 [meta.py:probe():210] probe
2021-06-17 16:45:36,762 DEBUG   HandlerThread:2324483 [git.py:repo():33] git repository is invalid
2021-06-17 16:45:36,762 DEBUG   HandlerThread:2324483 [meta.py:_save_pip():57] save pip
2021-06-17 16:45:36,765 DEBUG   HandlerThread:2324483 [meta.py:_save_pip():71] save pip done
2021-06-17 16:45:36,766 DEBUG   HandlerThread:2324483 [meta.py:_save_conda():78] save conda
2021-06-17 16:45:40,903 DEBUG   HandlerThread:2324483 [meta.py:_save_conda():86] save conda done
2021-06-17 16:45:40,903 DEBUG   HandlerThread:2324483 [meta.py:probe():252] probe done
2021-06-17 16:47:29,761 WARNING MainThread:2324483 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-06-17 16:47:29,903 WARNING MainThread:2324483 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-06-17 16:47:29,904 ERROR   MainThread:2324483 [internal.py:wandb_internal():150] Internal process interrupted.
2021-06-17 16:47:29,997 INFO    HandlerThread:2324483 [handler.py:finish():638] shutting down handler
2021-06-17 16:47:29,999 INFO    WriterThread:2324483 [datastore.py:close():288] close: /home/chengzilong/DDQN/wandb/offline-run-20210617_164532-3u0x1kar/run-3u0x1kar.wandb
2021-06-17 16:47:30,248 INFO    MainThread:2324483 [internal.py:handle_exit():78] Internal process exited
