(Collecting Data) ep=     0 ep_reward_last=0.00 ep_reward_avg=0.00 ep_steps= 112 total_steps=    113 loss=0.0000 eps=1.0000 fps=486.89
(Collecting Data) ep=     1 ep_reward_last=1.00 ep_reward_avg=0.50 ep_steps= 143 total_steps=    256 loss=0.0000 eps=1.0000 fps=512.79
(Collecting Data) ep=     2 ep_reward_last=1.00 ep_reward_avg=0.67 ep_steps= 158 total_steps=    414 loss=0.0000 eps=1.0000 fps=522.97
(Collecting Data) ep=     3 ep_reward_last=0.00 ep_reward_avg=0.50 ep_steps= 111 total_steps=    525 loss=0.0000 eps=1.0000 fps=473.72
(Collecting Data) ep=     4 ep_reward_last=1.00 ep_reward_avg=0.60 ep_steps= 138 total_steps=    663 loss=0.0000 eps=1.0000 fps=505.53
(Collecting Data) ep=     5 ep_reward_last=4.00 ep_reward_avg=1.17 ep_steps= 245 total_steps=    908 loss=0.0000 eps=1.0000 fps=513.29
[241, 310, 105, 738, 405, 490, 158, 92, 68, 20, 411, 562, 939, 296, 819, 783, 60, 227, 532, 549, 368, 283, 798, 176, 846, 108, 268, 219, 965, 949, 26, 848]
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chengzilong/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/chengzilong/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/chengzilong/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chengzilong/DDQN/test3.py", line 195, in <module>
    **vars(args)
  File "/home/chengzilong/DDQN/test3.py", line 110, in learn
    self.train()
  File "/home/chengzilong/DDQN/test3.py", line 102, in train
    loss = self.compute_td_loss()
  File "/home/chengzilong/DDQN/test3.py", line 134, in compute_td_loss
    state, action, reward, next_state, done = self.replay_buffer.sample()
  File "/home/chengzilong/DDQN/ReplayBufferAsync2.py", line 98, in sample
    is_construct_cache, data = self.__pipe.recv()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt:
Process ReplayBufferAsync-2:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chengzilong/DDQN/ReplayBufferAsync2.py", line 48, in run
    state_share = torch.zeros((self.cache_size, *state.shape), dtype=torch.tensor(state).dtype, device=torch.device(0)).share_memory_()
KeyboardInterrupt