2021-06-18 03:40:56,928 INFO    MainThread:3978271 [internal.py:wandb_internal():91] W&B internal server running at pid: 3978271, started at: 2021-06-18 03:40:56.927792
2021-06-18 03:40:56,931 DEBUG   HandlerThread:3978271 [handler.py:handle_request():124] handle_request: run_start
2021-06-18 03:40:56,932 INFO    WriterThread:3978271 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/offline-run-20210618_034056-21sxarkj/run-21sxarkj.wandb
2021-06-18 03:40:58,044 DEBUG   HandlerThread:3978271 [meta.py:__init__():39] meta init
2021-06-18 03:40:58,044 DEBUG   HandlerThread:3978271 [meta.py:__init__():53] meta init done
2021-06-18 03:40:58,044 DEBUG   HandlerThread:3978271 [meta.py:probe():210] probe
2021-06-18 03:40:58,050 DEBUG   HandlerThread:3978271 [git.py:repo():33] git repository is invalid
2021-06-18 03:40:58,050 DEBUG   HandlerThread:3978271 [meta.py:_save_pip():57] save pip
2021-06-18 03:40:58,051 DEBUG   HandlerThread:3978271 [meta.py:_save_pip():71] save pip done
2021-06-18 03:40:58,051 DEBUG   HandlerThread:3978271 [meta.py:_save_conda():78] save conda
2021-06-18 03:41:02,046 DEBUG   HandlerThread:3978271 [meta.py:_save_conda():86] save conda done
2021-06-18 03:41:02,047 DEBUG   HandlerThread:3978271 [meta.py:probe():252] probe done
2021-06-18 03:41:10,702 WARNING MainThread:3978271 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-06-18 03:41:10,904 WARNING MainThread:3978271 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-06-18 03:41:10,905 ERROR   MainThread:3978271 [internal.py:wandb_internal():150] Internal process interrupted.
2021-06-18 03:41:10,938 INFO    SenderThread:3978271 [sender.py:finish():933] shutting down sender
2021-06-18 03:41:11,707 INFO    WriterThread:3978271 [datastore.py:close():288] close: /home/chengzilong/DDQN/wandb/offline-run-20210618_034056-21sxarkj/run-21sxarkj.wandb
2021-06-18 03:41:11,709 INFO    MainThread:3978271 [internal.py:handle_exit():78] Internal process exited
